version: '3.8'

services:
  mysql_homework:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: homework_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_homework_data:/var/lib/mysql
    networks:
      - crm_network
    command: --default-authentication-plugin=mysql_native_password

  homework_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: homework_homework_service:latest
    ports:
      - "8003:8000"
    depends_on:
      - mysql_homework
    environment:
      - DB_HOST=mysql_homework
      - DB_USER=crm_user
      - DB_PASSWORD=password
      - DB_NAME=homework_db
      - ROOT_PASSWORD=password
    volumes:
      - ../../certs:/certs-in:ro
    networks:
      - crm_network
    restart: unless-stopped

volumes:
  mysql_homework_data:

networks:
  crm_network:
    external: true