version: '3.8'

services:
  mysql_messaging:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: messaging_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    volumes:
      - mysql_messaging_data:/var/lib/mysql
    networks:
      - crm_network
    command: --default-authentication-plugin=mysql_native_password

  messaging_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: messaging_messaging_service:latest
    ports:
      - "8004:8000"
    depends_on:
      - mysql_messaging
    environment:
      - DB_HOST=mysql_messaging
      - DB_USER=crm_user
      - DB_PASSWORD=password
      - DB_NAME=messaging_db
      - ROOT_PASSWORD=password
    volumes:
      - ../../certs:/certs-in:ro
    networks:
      - crm_network
    restart: unless-stopped

volumes:
  mysql_messaging_data:

networks:
  crm_network:
    external: true