version: '3.8'

services:
  mysql_courses:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: courses_db
      MYSQL_USER: crm_user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_courses_data:/var/lib/mysql
    networks:
      - crm_network
    command: --default-authentication-plugin=mysql_native_password

  courses_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: courses_courses_service:latest
    ports:
      - "8002:8000"
    depends_on:
      - mysql_courses
    environment:
      - DB_HOST=mysql_courses
      - DB_USER=crm_user
      - DB_PASSWORD=password
      - DB_NAME=courses_db
      - ROOT_PASSWORD=password
    volumes:
      - ../../certs:/certs-in:ro
    networks:
      - crm_network
    restart: unless-stopped

volumes:
  mysql_courses_data:

networks:
  crm_network:
    external: true