# Generated by Django 5.2 on 2025-04-16 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_administrator_classroom_remove_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_room',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
