# Generated by Django 5.2 on 2025-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_chapter_alter_parent_students_course_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pdf',
            field=models.CharField(max_length=255),
        ),
    ]
