# Generated by Django 5.2 on 2025-05-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentComment',
        ),
    ]
