# Generated by Django 5.2 on 2025-06-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
