# Generated by Django 5.2 on 2025-06-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
