# Generated by Django 5.2 on 2025-06-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_subject_grade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
